name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

env:
  PNPM_VERSION: 8.11.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            .nvmrc

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint
